path:
  ckpt_path: "/mnt/fast/nobackup/scratch4weeks/hl01486/exps/audio_generation/audioset_16k/v2_cliplevel/ckpt/2_clipnormpre_ch64_mel64_s100"
  log_path: "/mnt/fast/nobackup/scratch4weeks/hl01486/exps/audio_generation/audioset_16k/v2_cliplevel/log/2_clipnormpre_ch64_mel64_s100"
  result_path: "/mnt/fast/nobackup/scratch4weeks/hl01486/exps/audio_generation/audioset_16k/v2_cliplevel/result/2_clipnormpre_ch64_mel64_s100"

optimizer:
  batch_size: 4
  lr: 0.0001
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [30000000] # No lr decay
  anneal_rate: 0.5
  
step:
  total_step: 3000000
  log_step: 500
  synth_step: 10000
  val_step: 10000
  save_step: 20000

augmentation:
  mixup: 0.5
  balanced_sampling: True
