autoencoder:
  autoencoder_config_path: "/mnt/fast/nobackup/users/hl01486/projects/general_audio_generation/conditional_transfer/FastSpeech2/encoder_decoder/config/autoencoderkl/kl-f4-ch128-ts4/config.yaml"
  autoencoder_log_dir: "/mnt/fast/nobackup/users/hl01486/projects/general_audio_generation/conditional_transfer/FastSpeech2/encoder_decoder/log"

path:
  ckpt_path: "/mnt/fast/nobackup/scratch4weeks/hl01486/exps/audio_generation/audioset_16k/v3_cliplevel/ckpt/1_as_ae_timeshuffle4_s1004_s100"
  log_path: "/mnt/fast/nobackup/scratch4weeks/hl01486/exps/audio_generation/audioset_16k/v3_cliplevel/log/1_as_ae_timeshuffle4_s100"
  result_path: "/mnt/fast/nobackup/scratch4weeks/hl01486/exps/audio_generation/audioset_16k/v3_cliplevel/result/1_as_ae_timeshuffle4_s100"

optimizer:
  batch_size: 64
  lr: 0.0001
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [30000000] # No lr decay
  anneal_rate: 0.5
  
step:
  total_step: 3000000
  log_step: 500
  synth_step: 10000
  val_step: 10000
  save_step: 50000

augmentation:
  mixup: 0.5
  balanced_sampling: True
