path:
  ckpt_path: "./output/ckpt/test"
  log_path: "./output/log/test"
  result_path: "./output/result/test"
  
  # ckpt_path: "./output/ckpt/exp2_esc50_label"
  # log_path: "./output/log/exp2_esc50_label"
  # result_path: "./output/result/exp2_esc50_label"

  # ckpt_path: "./output/ckpt/exp3_esc50_label_latent_pred"
  # log_path: "./output/log/exp3_esc50_label_latent_pred"
  # result_path: "./output/result/exp3_esc50_label_latent_pred"

  # ckpt_path: "./output/ckpt/exp5_16k_with_vocoder_label_only"
  # log_path: "./output/log/exp5_16k_with_vocoder_label_only"
  # result_path: "./output/result/exp5_16k_with_vocoder_label_only"

  # ckpt_path: "./output/ckpt/exp7_16k_wavenet"
  # log_path: "./output/log/exp7_16k_wavenet"
  # result_path: "./output/result/exp7_16k_wavenet"

optimizer:
  batch_size: 4
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 8
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 10
  synth_step: 1000
  val_step: 4000
  save_step: 20000
