path:
  # ckpt_path: "./output/ckpt/esc50_disc"
  # log_path: "./output/log/esc50_disc"
  # result_path: "./output/result/esc50_disc"
  ckpt_path: "./output/ckpt/exp3_esc50_label_latent_pred"
  log_path: "./output/log/exp3_esc50_label_latent_pred"
  result_path: "./output/result/exp3_esc50_label_latent_pred"
optimizer:
  batch_size: 4
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 8
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 100
  synth_step: 1000
  val_step: 4000
  save_step: 20000
