dataset: "vggsound"
class_num: 309

path:
  corpus_path: "/vol/research/dcase2022/datasets/urbansound8k/UrbanSound8K/categorized"
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  raw_path: "./raw_data/us8k"
  preprocessed_path: "./preprocessed_data/us8k"

  train_data: "/mnt/fast/nobackup/users/hl01486/metadata/vggsound/datafiles/vggsound_train_data.json"
  test_data: "/mnt/fast/nobackup/users/hl01486/metadata/vggsound/datafiles/vggsound_test_data.json"
  class_label_index: "/mnt/fast/nobackup/users/hl01486/metadata/vggsound/class_labels_indices.csv"
  
preprocessing:
  val_size: 32
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 16000
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 160
    win_length: 1024
  mel:
    n_mel_channels: 64
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
    freqm: 0
    timem: 0
    mean: -4.14
    std: 2.04
    target_length: 1000
  pitch:
    feature: "frame_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "frame_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
