path:
  ckpt_path: "/mnt/fast/nobackup/scratch4weeks/hl01486/exps/audio_generation/vggsound_32k/v1/ckpt/1_basic"
  log_path: "/mnt/fast/nobackup/scratch4weeks/hl01486/exps/audio_generation/vggsound_32k/v1/log/1_basic"
  result_path: "/mnt/fast/nobackup/scratch4weeks/hl01486/exps/audio_generation/vggsound_32k/v1/result/1_basic"

  # ckpt_path: "/mnt/fast/nobackup/scratch4weeks/hl01486/exps/audio_generation/vggsound_32k/v1/ckpt/test"
  # log_path: "/mnt/fast/nobackup/scratch4weeks/hl01486/exps/audio_generation/vggsound_32k/v1/log/test"
  # result_path: "/mnt/fast/nobackup/scratch4weeks/hl01486/exps/audio_generation/vggsound_32k/v1/result/test"

  wav_path: "/mnt/fast/nobackup/scratch4weeks/hl01486/exps/audio_generation/vggsound_32k"

optimizer:
  batch_size: 6
  lr: 0.0001
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [500000, 800000, 1200000, 1500000]
  anneal_rate: 0.5
  
step:
  total_step: 1800000
  log_step: 100
  synth_step: 5000
  val_step: 5000
  save_step: 10000

augmentation:
  mixup: 0.0
  balanced_sampling: True