path:
  # ckpt_path: "./output/ckpt/test"
  # log_path: "./output/log/test"
  # result_path: "./output/result/test"

  # ckpt_path: "./output/ckpt/exp4_16k_with_vocoder"
  # log_path: "./output/log/exp4_16k_with_vocoder"
  # result_path: "./output/result/exp4_16k_with_vocoder"

  # ckpt_path: "./output/ckpt/us8k_exp1_glow"
  # log_path: "./output/log/us8k_exp1_glow"
  # result_path: "./output/result/us8k_exp1_glow"

  ckpt_path: "./output/ckpt/us8k_exp6_diff"
  log_path: "./output/log/us8k_exp6_diff"
  result_path: "./output/result/us8k_exp6_diff"

optimizer:
  batch_size: 8
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 2
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 100
  synth_step: 5000
  val_step: 10000
  save_step: 10000
