log_directory: "/mnt/fast/nobackup/scratch4weeks/hl01486/exps/audio_generation/stablediffusion/autoencoderkl16k"

id: 
  version: "v1.0.1"
  name: "kl-f4-ch128-ts4"
  root: "/mnt/fast/nobackup/users/hl01486/projects/general_audio_generation/conditional_transfer/FastSpeech2/encoder_decoder"

model:
  base_learning_rate: 4.5e-05
  target: encoder_decoder.ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: val/rec_loss
    embed_dim: 8
    time_shuffle: 4
    lossconfig:
      target: encoder_decoder.ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 1.0e-06
        disc_weight: 0.5
        disc_in_channels: 1
    ddconfig:
      double_z: true
      z_channels: 3
      resolution: 256
      in_channels: 4
      out_ch: 4
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
data:
  batchsize: 4
  target: main.DataModuleFromConfig
  params:
    batch_size: 10
    wrap: true
    train:
      target: encoder_decoder.ldm.data.openimages.FullOpenImagesTrain
      params:
        size: 384
        crop_size: 256
    validation:
      target: encoder_decoder.ldm.data.openimages.FullOpenImagesValidation
      params:
        size: 384
        crop_size: 256
